spring.application.name=pedidosya
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/dbPedidosya_in5am?createDatabaseIfNotExist=true
spring.datasource.username=IN5AM
spring.datasource.password=_odmon5Am

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true