spring.application.name=pedidosya
server.port=6767

spring.datasource.url=jdbc:mysql://localhost:3306/dbPedidosya_in5am?createDatabaseIfNotExist=true
spring.datasource.username=IN5AM
spring.datasource.password=_odmon5Am

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# Configuracion de JSON Web Token (JWT)
# Clave secreta de firma HMAC-SHA256 protegida y cifrada mediante BCrypt (Factor de costo / Rounds: 12)
jwt.secret=$2a$12$e8kqX9J1Z1qK8Q7b1m4o5u0WcvOba81EeXqE9EUB7bdTi8S2gzcj6
jwt.expiration=86400000